# --- Adding stuff to PATH
if [ -d "$HOME/.local/bin" ]; then
	case ":$PATH:" in
		*":$HOME/.local/bin:"*) :;;
		*) export PATH="$HOME/.local/bin:$PATH" ;;
	esac
fi

if [ -d "/usr/local/go/bin" ]; then # Or check if go is installed another way
  case ":$PATH:" in
    *":/usr/local/go/bin:"*) :;;
    *) export PATH="$PATH:/usr/local/go/bin" ;; # Appending here is fine
  esac
fi
